import type { Course } from "./advanced-courses";
import type { Lesson } from "./course";

type LessonSeed = [
  title: string,
  subtitle: string,
  code: string,
  output: string,
  concept: string,
  question: string,
  answer: string,
  wrong: string,
  correct: number,
];

function lessons(
  language: Lesson["language"],
  seeds: LessonSeed[],
  exercises: string[],
): Lesson[] {
  return seeds.map(
    (
      [
        title,
        subtitle,
        code,
        output,
        concept,
        question,
        answer,
        wrong,
        correct,
      ],
      index,
    ) => ({
      language,
      title,
      subtitle,
      tag: index < 2 ? "FOUNDATIONS" : index < 6 ? "PRACTICE" : "PROJECT",
      minutes: 45,
      intro: `${subtitle} — ลองแก้ตัวอย่างและสังเกตผลก่อนนำแนวคิดไปใช้ในโปรเจกต์จริง`,
      concepts: [
        concept,
        "ทดลองเปลี่ยน input แล้วรันซ้ำเพื่อดูพฤติกรรม",
        "อ่าน error และตรวจค่าก่อนเพิ่มความซับซ้อน",
      ],
      code,
      output,
      exercise: `ปรับตัวอย่างเรื่อง “${title}” ให้รับข้อมูลอีกหนึ่งกรณี เพิ่มการตรวจ input ที่ไม่ถูกต้อง แล้วอธิบายผลที่คาดหวังก่อนรัน`,
      question,
      choices: [answer, wrong, "ขึ้นอยู่กับค่าที่ส่งเข้า"].map(
        (_, choiceIndex, choices) =>
          choices[
            (choiceIndex + ((index + 1) % choices.length)) % choices.length
          ],
      ),
      answer: (correct - ((index + 1) % 3) + 3) % 3,
      explanation: concept,
    }),
  );
}

const javascript: LessonSeed[] = [
  [
    "เริ่มต้น JavaScript",
    "ตัวแปรและ console",
    'const learner = "คุณ";\nconsole.log(`สวัสดี ${learner}`);',
    "สวัสดี คุณ",
    "ใช้ const กับค่าที่ไม่กำหนดตัวแปรใหม่ และ let เมื่อจำเป็นต้องเปลี่ยนค่า",
    "ประกาศค่าคงที่ใช้คำสั่งใด?",
    "const",
    "var เท่านั้น",
    0,
  ],
  [
    "ชนิดข้อมูลและเงื่อนไข",
    "string, number, boolean",
    'const minutes = 45;\nconsole.log(minutes >= 30 ? "พร้อม" : "พัก");',
    "พร้อม",
    "JavaScript แปลงชนิดบางกรณีอัตโนมัติ จึงควรเปรียบเทียบแบบเคร่งครัดด้วย ===",
    "เครื่องหมายใดเปรียบเทียบทั้งค่าและชนิด?",
    "===",
    "=",
    0,
  ],
  [
    "Array และ Object",
    "จัดกลุ่มข้อมูลที่เกี่ยวข้อง",
    'const task = { title: "เรียน JS", done: false };\nconst tasks = [task];\nconsole.log(tasks[0].title);',
    "เรียน JS",
    "Array เก็บลำดับรายการ และ object เก็บค่าผ่าน property ที่มีชื่อ",
    "อ่านงานแรกจาก tasks อย่างไร?",
    "tasks[0]",
    "tasks.first()",
    0,
  ],
  [
    "ฟังก์ชันและขอบเขต",
    "รับค่าแล้วคืนผล",
    "function addTax(price) { return price * 1.07; }\nconsole.log(addTax(100));",
    "107",
    "พารามิเตอร์รับข้อมูลเข้า return ส่งค่ากลับ และ block scope ช่วยจำกัดตัวแปร",
    "return ทำหน้าที่อะไร?",
    "ส่งผลลัพธ์กลับ",
    "พิมพ์หน้าจอ",
    0,
  ],
  [
    "วนซ้ำและจัดการ Array",
    "map, filter และ for...of",
    "const scores = [50, 80];\nconsole.log(scores.map((score) => score + 5));",
    "[55, 85]",
    "map สร้าง array ใหม่จากการแปลงสมาชิก ส่วน filter เลือกสมาชิกที่ผ่านเงื่อนไข",
    "ต้องการแปลงสมาชิกทุกตัวใช้เมธอดใด?",
    "map",
    "filter",
    0,
  ],
  [
    "TypeScript เบื้องต้น",
    "ระบุชนิดเพื่อจับข้อผิดพลาด",
    'type Task = { title: string; done: boolean };\nconst task: Task = { title: "ส่งงาน", done: false };\nconsole.log(task.done);',
    "false",
    "TypeScript ตรวจชนิดก่อนรัน และ type ช่วยระบุรูปร่างข้อมูล",
    "Task กำหนดชนิด done เป็นอะไร?",
    "boolean",
    "string",
    0,
  ],
  [
    "Async และ Promise",
    "รอการทำงานแบบไม่บล็อก",
    'async function loadName() { return "DevPath"; }\nloadName().then(console.log);',
    "DevPath",
    "async function คืน Promise และ await ใช้รอผลภายในฟังก์ชัน async",
    "ค่าที่ async function คืนคืออะไร?",
    "Promise",
    "ตัวเลขเสมอ",
    0,
  ],
  [
    "โปรเจกต์สรุป JavaScript",
    "ทำรายการและตรวจข้อมูล",
    'type Task = { title: string; done: boolean };\nconst tasks: Task[] = [{ title: "เรียน", done: true }];\nconsole.log(tasks.filter((task) => !task.done).length);',
    "0",
    "แยกชนิดข้อมูล ฟังก์ชัน และการแสดงผลเพื่อให้ส่วนย่อยทดสอบและดูแลง่าย",
    "filter ในตัวอย่างเลือกงานแบบใด?",
    "งานที่ยังไม่เสร็จ",
    "งานทั้งหมด",
    0,
  ],
];

const node: LessonSeed[] = [
  [
    "Node.js runtime, npm และ ESM",
    "เริ่มโปรเจกต์และตั้งค่า environment",
    "const port = Number(process.env.PORT ?? 3000);\nconsole.log(`Node ${process.version} on ${port}`);",
    "Node v24.x on 3000",
    'Node.js รัน JavaScript ฝั่ง server; ตั้ง package.json เป็น type "module" เพื่อใช้ ESM และอ่าน config จาก environment',
    "ใช้ syntax ใดนำเข้าฟังก์ชันใน ESM?",
    "import",
    "require เท่านั้น",
    0,
  ],
  [
    "Event loop และ asynchronous I/O",
    "อ่านไฟล์และ stream โดยไม่บล็อกงานอื่น",
    'import { createReadStream, createWriteStream } from "node:fs";\ncreateReadStream("input.txt").pipe(createWriteStream("copy.txt"));',
    "คัดลอกข้อมูลเป็น chunks",
    "I/O แบบ asynchronous คืนเวลาให้ event loop ทำงานอื่น; stream จัดการข้อมูลเป็นส่วนโดยไม่โหลดไฟล์ทั้งหมดเข้าหน่วยความจำ",
    "เหตุใด stream จึงเหมาะกับไฟล์ใหญ่?",
    "ประมวลผลข้อมูลเป็นส่วน",
    "โหลดไฟล์ทั้งหมดก่อนเสมอ",
    0,
  ],
  [
    "HTTP, REST และ Fastify routes",
    "จับคู่ method/path กับ handler และ status code",
    'import Fastify from "fastify";\nconst app = Fastify();\napp.get("/health", async (_request, reply) => reply.code(200).send({ ok: true }));\nawait app.listen({ port: 3000 });',
    "GET /health → 200 { ok: true }",
    "HTTP request มี method/path และ response มี status/body; REST ใช้ resource paths และ Fastify routes ผูกกับ handler",
    "GET /health โดยทั่วไปใช้ทำอะไร?",
    "ตรวจว่าสามารถเรียก API ได้",
    "ลบ health resource",
    0,
  ],
  [
    "Contract, validation และ error handling",
    "กำหนด request/response schema ของ API",
    'app.post("/tasks", { schema: { body: { type: "object", required: ["title"], properties: { title: { type: "string", minLength: 1 } } } } }, async (request, reply) => reply.code(201).send(await createTask(request.body)));',
    "valid request → 201; invalid request → 400",
    "กำหนด schema ของ request ตรวจข้อมูลก่อนเรียก service และตอบ status/error ที่ไม่เผยรายละเอียดภายใน",
    "เหตุใดจึงตรวจ body?",
    "ป้องกันข้อมูลผิดรูปแบบ",
    "ข้าม validation ทุก request",
    0,
  ],
  [
    "SQLite, CRUD และ prepared statements",
    "เก็บงานถาวรโดยแยกค่าจาก SQL",
    'const insert = db.prepare("INSERT INTO tasks (title) VALUES (?)");\nconst result = insert.run(title);\nconst task = db.prepare("SELECT id, title FROM tasks WHERE id = ?").get(result.lastInsertRowid);',
    "เพิ่มงานแล้วอ่านกลับด้วย id",
    "ใช้ SQLite เก็บ CRUD แบบถาวร และ prepared statement ส่ง user input เป็น parameter ไม่ต่อ string เป็น SQL",
    "เครื่องหมาย ? ใน prepared statement ช่วยอะไร?",
    "แยกค่าข้อมูลออกจาก SQL",
    "ซ่อน query จากฐานข้อมูล",
    0,
  ],
  [
    "Authentication และ authorization",
    "แยกการยืนยันตัวตนจากสิทธิ์เข้าถึง",
    'app.get("/admin", { preHandler: [authenticate, requireRole("admin")] }, async () => ({ ok: true }));',
    "ไม่ login → 401; ไม่มี role → 403",
    "ตรวจ session เพื่อยืนยันว่าเป็นใคร แล้วตรวจ role ว่าทำสิ่งนั้นได้หรือไม่ เก็บ secret นอก source และจำกัดสิทธิ์เท่าที่จำเป็น",
    "authorization ตอบคำถามใด?",
    "ผู้ใช้นี้ทำสิ่งนี้ได้หรือไม่",
    "ผู้ใช้นี้คือใคร",
    0,
  ],
  [
    "ทดสอบ, logging และ graceful shutdown",
    "ตรวจ service ด้วย node:test และปิด server อย่างเรียบร้อย",
    'import test from "node:test";\nimport assert from "node:assert/strict";\ntest("creates a task", () => { assert.equal(createTask("เรียน").title, "เรียน"); });',
    "✔ creates a task",
    "node:test ตรวจพฤติกรรมโดยไม่พึ่ง framework; log ต้องไม่เผย secret และ shutdown ควรหยุดรับ request ก่อนปิด resource",
    "graceful shutdown มีเป้าหมายใด?",
    "ปิด server และ resource โดยไม่ทิ้งงานค้าง",
    "kill process ทันทีทุกครั้ง",
    0,
  ],
  [
    "Task Management API capstone",
    "ส่งมอบ CRUD ที่ใช้ database, auth และ tests",
    'app.get("/tasks", { preHandler: [authenticate] }, listTasks);\napp.post("/tasks", { preHandler: [authenticate], schema: createTaskSchema }, createTask);\napp.patch("/tasks/:id", updateTask);\napp.delete("/tasks/:id", removeTask);',
    "typed API: CRUD + SQLite + auth + automated tests",
    "ประกอบ Fastify routes, validation, SQLite prepared statements, authentication/authorization, error handling, logging, automated tests และ graceful shutdown เป็นโปรเจกต์เดียว",
    "ข้อใดทำให้ capstone นี้ครบสัญญา?",
    "CRUD, validation, database, auth และ tests",
    "มี route GET เพียง endpoint เดียว",
    0,
  ],
];

const next: LessonSeed[] = [
  [
    "React components, state และ forms",
    "ใช้ props และ events สร้าง UI ที่ตอบสนอง",
    '"use client";\nimport { useState } from "react";\nexport function TaskForm({ onAdd }: { onAdd: (title: string) => void }) {\n  const [title, setTitle] = useState("");\n  return <form onSubmit={(event) => { event.preventDefault(); onAdd(title); setTitle(""); }}><label htmlFor="title">งานใหม่</label><input id="title" value={title} onChange={(event) => setTitle(event.target.value)} /><button>เพิ่มงาน</button></form>;\n}',
    "controlled form เรียก onAdd(title)",
    "component รับข้อมูลผ่าน props, เก็บ state ด้วย hook, จัดการ event และใช้ label ที่เชื่อมกับ input เพื่อรองรับ keyboard และ screen reader",
    "controlled input อ่านค่าปัจจุบันจากที่ใด?",
    "React state",
    "DOM โดยไม่จัดการ state",
    0,
  ],
  [
    "App Router, navigation และ dynamic routes",
    "เชื่อม layout/page กับเส้นทางตามโฟลเดอร์",
    'import Link from "next/link";\nexport default function TasksPage() { return <main><h1>งานของฉัน</h1><Link href="/tasks/1">เปิดงานแรก</Link></main>; }',
    "ลิงก์ไป /tasks/1",
    "App Router สร้าง route จากโฟลเดอร์, layout ครอบหน้า, Link นำทาง และ [id] รับ dynamic segment",
    "โฟลเดอร์ [id] ใช้ทำอะไร?",
    "รับ dynamic route segment",
    "ตั้งค่า environment variable",
    0,
  ],
  [
    "Server และ Client Components",
    "แบ่ง data access และ interaction ให้ถูกขอบเขต",
    "export default async function Page() {\n  const tasks = await getTasks();\n  return <TaskList tasks={tasks} />;\n}",
    "Server Component ส่งข้อมูลให้ UI; interaction hydrate ฝั่ง client",
    "Server Component ดึงข้อมูลและถือ secret ได้; state, event handler และ browser APIs อยู่ใน Client Component โดยส่งข้อมูลที่ serialize ได้ผ่าน props",
    "เมื่อใช้ onClick ต้องใช้องค์ประกอบแบบใด?",
    "Client Component",
    "Server Component เท่านั้น",
    0,
  ],
  [
    "Data fetching, streaming และ cache",
    "โหลดข้อมูลฝั่ง server พร้อม fallback และ revalidation",
    'import { cacheLife } from "next/cache";\nimport { Suspense } from "react";\nasync function TaskList() { "use cache"; cacheLife("hours"); const tasks = await getTasks(); return <ul>{tasks.map((task) => <li key={task.id}>{task.title}</li>)}</ul>; }\nexport default function Page() { return <Suspense fallback={<p role="status">กำลังโหลด…</p>}><TaskList /></Suspense>; }',
    "stream รายการงานเมื่อข้อมูลพร้อม",
    "เปิด cacheComponents ใน next.config.ts ก่อนใช้ use cache/cacheLife; Suspense/loading ส่ง fallback ระหว่างรอ และ revalidation ใช้ปรับข้อมูลที่เก็บไว้",
    "Suspense ช่วยเรื่องใดเมื่อข้อมูลช้า?",
    "stream ส่วนที่พร้อมและแสดง fallback",
    "ยืนยันตัวตนให้ผู้ใช้",
    0,
  ],
  [
    "Server Actions และ form validation",
    "ทำ mutation ฝั่ง server แล้วปรับข้อมูลที่แสดง",
    '"use server";\nimport { revalidatePath } from "next/cache";\nexport async function addTask(formData: FormData) {\n  const title = String(formData.get("title") ?? "").trim();\n  if (!title) return { error: "กรุณากรอกชื่องาน" };\n  await saveTask({ title });\n  revalidatePath("/tasks");\n}',
    "ตรวจ title ก่อน save และ revalidate /tasks",
    "Server Actions รับข้อมูลจาก form ได้ แต่ต้อง validate ที่ server และตรวจสิทธิ์ทุกครั้งก่อน mutation; revalidatePath ทำให้หน้าอ่านข้อมูลใหม่",
    "ก่อนบันทึกผ่าน Server Action ควรทำอะไร?",
    "validate input และตรวจ authorization ฝั่ง server",
    "เชื่อค่า input จาก browser ทันที",
    0,
  ],
  [
    "Route Handlers และ security",
    "สร้าง API endpoint พร้อมตรวจ session และสิทธิ์",
    'export async function GET(request: Request) {\n  const session = await verifySession(request);\n  if (!session) return Response.json({ error: "Unauthorized" }, { status: 401 });\n  return Response.json(await listTasksFor(session.userId));\n}',
    "ไม่มี session → 401; มี session → JSON ของผู้ใช้",
    "Route Handler แยก API ออกจาก UI; ตรวจ authentication/authorization ก่อนอ่านข้อมูล และเก็บ credentials ใน environment ฝั่ง server",
    "ก่อนส่งข้อมูลส่วนตัวกลับ API ต้องตรวจอะไร?",
    "session และสิทธิ์ของผู้ใช้",
    "สีของปุ่ม submit",
    0,
  ],
  [
    "Accessibility, metadata และ Playwright",
    "ทำเว็บให้ใช้งานได้ ตรวจคุณภาพ และวัดผล",
    'import { test, expect } from "@playwright/test";\ntest("dashboard shows tasks", async ({ page }) => { await page.goto("/"); await expect(page.getByRole("heading", { name: "Task Dashboard" })).toBeVisible(); });',
    "เปิดหน้าเว็บแล้วพบ heading Task Dashboard",
    "ใช้ semantic HTML และ keyboard flow; metadata อธิบายหน้า; ลด JavaScript ที่ไม่จำเป็นและใช้ Playwright ตรวจเส้นทางหลัก",
    "Playwright ตรวจอะไรในบทนี้?",
    "พฤติกรรมเว็บผ่าน browser จริง",
    "ชนิด SQL column ตอน compile",
    0,
  ],
  [
    "Task Dashboard capstone",
    "สร้าง dashboard ที่เชื่อม API และรองรับสถานะข้อมูล",
    "export default async function Dashboard() {\n  const tasks = await listTasks();\n  return <main><h1>Task Dashboard</h1><TaskSummary tasks={tasks} /><TaskList tasks={tasks} /></main>;\n}",
    "Task Dashboard พร้อม summary และรายการงาน",
    "รวม Server Components, Client interactions, loading/error states, accessible forms และ API; ใช้ Node.js Task API หรือ mock API หากเรียนสายเว็บอย่างเดียว",
    "dashboard เรียนเดี่ยวโดยไม่ต่อ Node API ทำอย่างไร?",
    "ใช้ API ตัวอย่างหรือ mock API",
    "สร้าง backend จริงภายใน static export",
    0,
  ],
];

const javascriptExercises = [
  "เพิ่มตัวแปร name อีกหนึ่งค่า แล้วพิมพ์ข้อความทักทายโดยใช้ template literal",
  "รับคะแนน 0–100 แล้วแสดงระดับผ่าน/ไม่ผ่าน พร้อมทดสอบค่าที่ขอบเขต 59 และ 60",
  "เพิ่มงานอีกสองรายการใน array แล้วแสดงเฉพาะ title ของงานที่ยังไม่เสร็จ",
  "เขียนฟังก์ชันส่วนลดที่รับราคาและเปอร์เซ็นต์ ตรวจราคาเป็นลบและทดสอบ 0%",
  "ใช้ filter เลือกคะแนนตั้งแต่ 60 ขึ้นไป แล้วใช้ reduce หาค่าเฉลี่ยของรายการที่ผ่าน",
  "เพิ่ม priority: number ลงใน Task และให้ TypeScript ช่วยตรวจ object ที่ขาด property",
  "เปลี่ยนตัวอย่างให้รอ Promise ที่ resolve หลัง 300ms และจัดการกรณี reject ด้วย try/catch",
  "ทำ Task Board ที่เพิ่มงาน ทำเครื่องหมายเสร็จ และแสดงจำนวนงานที่ยังค้าง",
];
const nodeExercises = [
  "พิมพ์ process.version และ argv จาก script แล้วรันด้วย argument ชื่อที่คุณเลือก",
  "คัดลอกไฟล์ใหญ่ด้วย stream และเพิ่ม error handler; สังเกตว่า event loop ยังตอบงานอื่นได้",
  "สร้าง Fastify GET /health พร้อม status 200 และเพิ่ม GET /tasks/:id",
  "เพิ่ม request/response schema, ขอบเขต title และ error mapping สำหรับ 400/404",
  "สร้าง SQLite table แล้วเพิ่ม/อ่าน/แก้/ลบงานด้วย prepared statements",
  "เพิ่ม login/session และ role check; ทดสอบกรณี 401, 403 และผู้ใช้ที่ได้รับอนุญาต",
  "เขียน node:test ให้ service, เพิ่ม structured log และปิด server/resource เมื่อรับ SIGTERM",
  "ทำ CRUD ให้ครบพร้อม validation, SQLite, auth, tests, logging และ graceful shutdown",
];
const nextExercises = [
  "เพิ่มฟอร์มที่จัดการ title ด้วย state และส่ง onAdd ผ่าน props; ทดสอบ submit ด้วย keyboard และ title ว่าง",
  "เพิ่ม /tasks/[id] พร้อม layout, Link navigation และ not-found state เมื่อไม่พบงาน",
  "อ่าน task บน Server Component แล้วแยกปุ่ม checkbox เป็น Client Component พร้อม props แบบ serializable",
  "เปิด cacheComponents, ใช้ Suspense/loading fallback และตั้ง cacheLife; อธิบายเมื่อใดต้อง revalidate ข้อมูล",
  "สร้าง Server Action เพิ่มงาน ตรวจ title และ authorization ฝั่ง server แล้ว revalidatePath หลังบันทึก",
  "สร้าง GET /api/tasks ที่ตรวจ session, authorization และส่ง 401/403/200 ตามกรณี",
  "เพิ่ม metadata, semantic headings, keyboard flow และ Playwright test สำหรับการสร้างงาน",
  "สร้าง Task Dashboard ต่อ Node API หรือ mock API พร้อม loading/error, summary และ accessible task form",
];

export const newCourses: Course[] = [
  {
    id: 6,
    track: "javascript",
    title: "JavaScript & TypeScript",
    subtitle: "พื้นฐานร่วมก่อนเลือกสร้าง API หรือเว็บแอป",
    prerequisite: "เริ่มจากศูนย์ได้ ใช้ Node.js 24 LTS สำหรับตัวอย่าง",
    project: "Task Board แบบ typed",
    groups: [
      "JavaScript",
      "ข้อมูลและฟังก์ชัน",
      "TypeScript และ async",
      "โปรเจกต์สรุป",
    ],
    sources: [
      {
        title: "TypeScript Handbook",
        url: "https://www.typescriptlang.org/docs/handbook/intro.html",
      },
    ],
    lessons: lessons("typescript", javascript, javascriptExercises).map(
      (lesson, index) => ({
        ...lesson,
        language: index < 5 || index === 6 ? "javascript" : "typescript",
      }),
    ),
  },
  {
    id: 7,
    track: "node",
    title: "Node.js Backend",
    subtitle: "สร้าง Task API ด้วย TypeScript และ Fastify",
    prerequisite:
      "แนะนำ JavaScript & TypeScript ก่อนแต่ไม่บังคับ; ใช้ Node.js 24 LTS และติดตั้ง Fastify, better-sqlite3, TypeScript, tsx และ @types/node",
    project: "Task API พร้อม CRUD",
    groups: [
      "Runtime และ async I/O",
      "HTTP และ contracts",
      "SQLite และ security",
      "Tests และ Task API",
    ],
    sources: [
      {
        title: "Node.js Documentation",
        url: "https://nodejs.org/docs/latest/api/",
      },
      {
        title: "Node.js Test Runner",
        url: "https://nodejs.org/docs/latest/api/test.html",
      },
      {
        title: "Fastify Documentation",
        url: "https://fastify.dev/docs/latest/",
      },
      {
        title: "SQLite SQL Language",
        url: "https://www.sqlite.org/lang.html",
      },
    ],
    lessons: lessons("typescript", node, nodeExercises),
  },
  {
    id: 8,
    track: "nextjs",
    title: "Next.js Web",
    subtitle: "สร้าง Task Dashboard ด้วย Next.js App Router",
    prerequisite:
      "แนะนำ JavaScript & TypeScript ก่อนแต่ไม่บังคับ; ใช้ Node.js 24 LTS และ create-next-app; Server Actions/Route Handlers ต้อง deploy บน Node.js runtime ไม่ใช่ static export นี้",
    project: "Task Dashboard",
    groups: [
      "React foundations",
      "App Router",
      "Data และ mutations",
      "Security และ Dashboard",
    ],
    sources: [
      { title: "Next.js App Router", url: "https://nextjs.org/docs/app" },
      { title: "React Documentation", url: "https://react.dev/learn" },
      {
        title: "Next.js: Fetching Data",
        url: "https://nextjs.org/docs/app/getting-started/fetching-data",
      },
      {
        title: "Next.js: Static Exports",
        url: "https://nextjs.org/docs/app/guides/static-exports",
      },
      {
        title: "Next.js: Testing with Playwright",
        url: "https://nextjs.org/docs/app/guides/testing/playwright",
      },
    ],
    lessons: lessons("tsx", next, nextExercises),
  },
];
